name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          LABEL_FUNC: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
        