name: Manual
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: choice
        options:
          - info
          - warn
          - error
        default: info
        required: true
        description: Choice status
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
